//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class boleta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public boleta()
        {
            this.detalle_pago = new HashSet<detalle_pago>();
        }
    
        public decimal n_boleta { get; set; }
        public System.DateTime fecha_emision { get; set; }
        public string nombre_cliente { get; set; }
        public string descripcion { get; set; }
        public string direccion_empresa { get; set; }
        public string rut_empresa { get; set; }
        public decimal precio_total { get; set; }
        public decimal servicios_cod_servicio { get; set; }
        public decimal tipo_boleta_id_tipo_boleta { get; set; }
    
        public virtual servicio servicio { get; set; }
        public virtual tipo_boleta tipo_boleta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pago> detalle_pago { get; set; }
    }
}
