//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_permiso
    {
        public decimal id_detalle { get; set; }
        public string seccion { get; set; }
        public bool permiso { get; set; }
        public decimal modulo_id_modulo { get; set; }
        public decimal rol_cod_rol { get; set; }
    
        public virtual modulo modulo { get; set; }
        public virtual rol rol { get; set; }
    }
}
