//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_pago
    {
        public decimal id_detalle_pago { get; set; }
        public decimal boleta_n_boleta { get; set; }
        public decimal cantidad { get; set; }
        public decimal precio_unitario { get; set; }
        public decimal subtotal { get; set; }
        public decimal producto_almacen_id_producto_almacen { get; set; }
    
        public virtual boleta boleta { get; set; }
        public virtual producto_almacen producto_almacen { get; set; }
    }
}
