//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_pedido
    {
        public decimal id_detalle_pedido { get; set; }
        public decimal cantidad { get; set; }
        public decimal valor_compra { get; set; }
        public decimal subtotal { get; set; }
        public long iva { get; set; }
        public decimal total { get; set; }
        public string nombre_producto { get; set; }
        public decimal pedido_cabecera_id_pedido { get; set; }
        public decimal producto_cod_prod { get; set; }
    
        public virtual pedido_cabecera pedido_cabecera { get; set; }
        public virtual producto producto { get; set; }
    }
}
