//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.detalle_pedido = new HashSet<detalle_pedido>();
            this.producto_almacen = new HashSet<producto_almacen>();
        }
    
        public decimal cod_prod { get; set; }
        public string precio_unitario { get; set; }
        public string nombre_producto { get; set; }
        public string descripcion { get; set; }
        public decimal familia_producto_id_familia { get; set; }
        public decimal proveedor_id_proveedor { get; set; }
        public decimal marca_producto_id_marca { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pedido> detalle_pedido { get; set; }
        public virtual familia_producto familia_producto { get; set; }
        public virtual marca_producto marca_producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto_almacen> producto_almacen { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
