//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto_almacen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto_almacen()
        {
            this.detalle_pago = new HashSet<detalle_pago>();
        }
    
        public decimal id_producto_almacen { get; set; }
        public decimal producto_cod_prod { get; set; }
        public string almacen_id_almacén { get; set; }
        public decimal stock { get; set; }
        public bool estado { get; set; }
    
        public virtual almacen almacen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pago> detalle_pago { get; set; }
        public virtual producto producto { get; set; }
    }
}
